<?xml version="1.0"?>
<robot xmlns:xacro="TergeoRobot" name="tergeo">
  <!-- macro to generate world and robot main body -->
  <xacro:macro name="base_world" params="world_name body_name mass length width height above_groud_height">
    <!-- base world link in rviz -->
    <link name="${world_name}"/>

    <joint name="${world_name}_${body_name}_joint" type="fixed">
      <parent link="${world_name}"/>
      <child link="${body_name}_link"/>
      <origin xyz="0.0 0.0 ${height/2+above_groud_height-0.01}" rpy="0 0 0"/>
    </joint>

    <link name="${body_name}_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="0.00001" ixy="0.00000" ixz="0.00000"
                iyy="0.00001" iyz="0.00000"
                izz="0.00001" />
      </inertial>
    </link>

    <!-- robot body color in gazebo gui -->
    <gazebo reference="${body_name}_link">
      <material>Gazebo/Orange</material>
    </gazebo>

  </xacro:macro>

</robot>