<?xml version="1.0"?>
<robot xmlns:xacro="TergeoRobot" name="tergeo">
  <!-- args -->
  <xacro:property name="wheel_thickness" value=" 0.02" />
  <xacro:property name="wheel_radius" value="0.10" />

  <!-- Definition of the wheel macro -->
  <xacro:macro name="wheel_model" params="wheel_name parent_link wheel_xyz wheel_rpy wheel_axis">
    <!-- wheel joint -->
    <joint name="${wheel_name}_joint" type="continuous">
      <parent link="${parent_link}" />
      <child link="${wheel_name}_link" />
      <origin xyz="${wheel_xyz}" rpy="${wheel_rpy}" />
      <axis xyz="${wheel_axis}" />
    </joint>

    <!-- wheel link -->
    <link name="${wheel_name}_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
        <material name="green" />
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1" />
        <inertia ixx="0.0025" ixy="0" ixz="0"
                iyy="0.0025" iyz="0"
                izz="0.005" />
      </inertial>
    
      <!-- <inertial>
        <origin xyz="0 0 0" />
        <mass value="2" />
        <inertia ixx="${0.025/2}" ixy="0" ixz="0"
                iyy="${0.025/2}" iyz="0"
                izz="${0.05/2}" />
      </inertial> -->
    </link>

    <!-- setup the motor -->
    <transmission name="${wheel_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${wheel_name}_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${wheel_name}_motor">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- gazebo element -->
    <gazebo reference="${wheel_name}_link">
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <fdir1>1 0 0</fdir1>
      <material>Gazebo/Green</material>
    </gazebo>

  </xacro:macro>

  <!-- TODO: args communicate -->
  <xacro:macro name="wheel_control" params="left_wheel_name right_wheel_name" >
    <gazebo>
      <plugin name="robot_controller" filename="libgazebo_ros_diff_drive.so">
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <odometrySource>world</odometrySource>
        <publishOdomTF>true</publishOdomTF>
        <robotBaseFrame>base_world</robotBaseFrame>
        <publishWheelTF>false</publishWheelTF>
        <publishTf>true</publishTf>
        <publishWheelJointState>true</publishWheelJointState>
        <legacyMode>false</legacyMode>
        <updateRate>30</updateRate>
        <leftJoint>${left_wheel_name}_joint</leftJoint>
        <rightJoint>${right_wheel_name}_joint</rightJoint>
        <!-- wheel seperation need to know the body width -->
        <wheelSeparation>0.46</wheelSeparation>
        <wheelDiameter>${2*wheel_radius}</wheelDiameter>
        <wheelAcceleration>100</wheelAcceleration>
        <wheelTorque>5</wheelTorque>
        <rosDebugLevel>na</rosDebugLevel>
      </plugin>
    </gazebo>

  </xacro:macro>
</robot>