<?xml version="1.0"?>
<!-- Tergeo Washing Floor Robot -->
<robot name="tergeo" xmlns:xacro="TergeoRobot">
  
  <!-- Import all designed robot model args  -->
  <xacro:include filename="$(find robot_description)/urdf/t_robot_args.xacro"/>
  <!-- Import all macros to simply the xacro -->
  <!-- Macros depends on properties in t_robot_args.xacro -->
  <!-- <xacro:include filename="$(find robot_description)/urdf/t_robot_macros.xacro"/> -->
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find robot_description)/urdf/rviz_materials.xacro"/>
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find robot_description)/urdf/t_robot.gazebo.xacro"/>

  <!-- This link is similar with world link, just a name -->
  <link name="base_world"/>

  <!-- TODO: type="fixed" or type="floating" -->
  <joint name="world_robot_joint" type="fixed">
    <parent link="base_world"/>
    <child link="robot_body_link"/> 
    <origin xyz="0.0 0.0 ${height/2 + dis_robot_groud - 0.01}" rpy="0 0 0"/>
  </joint> 

  <!-- the robot body link -->
  <link name="robot_body_link"> 
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="8.2573504e-01"/>
      <inertia ixx="2.2124416e-03" ixy="-1.2294101e-05" ixz="3.4938785e-05"
               iyy="2.1193702e-03" iyz="-5.0120904e-06"
               izz="2.0064271e-03" />
    </inertial>
  </link>

  <!-- joint of robot body link and laser -->
  <joint name="body_scan_joint" type="continuous">
    <parent link="robot_body_link"/>
    <child link="robot_scan_link"/>
    <origin xyz="0 0 ${height/2+0.01+lidar_above}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- imu joint -->
  <joint name="imu_joint" type="fixed">
    <parent link="robot_body_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  <!-- imu link -->
  <link name="imu_link"/>

  <!-- laser sensor link -->
  <link name="robot_scan_link"> 
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.02"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.02"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <!-- TODO: the direction of the 2 wheels -->
  <!-- joint of robot body link and left wheel -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="robot_body_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 ${width/2+0.02} ${-height/2}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.05"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
    </inertial>
  </link>

  <!-- joint of robot body link and right wheel -->
  <joint name="wheel_right_joint" type="continuous">
    <parent link="robot_body_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 ${-width/2-0.02} ${-height/2}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.05"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
    </inertial>
  </link>

  <!-- 2 caster wheel of front and back -->
  <joint name="caster_back_joint" type="fixed">
    <parent link="robot_body_link"/>
    <child link="caster_back_link"/>
    <origin xyz="${-length/2} 0 ${-height/2-0.025}" rpy="0 0 0"/>
  </joint>

  <link name="caster_back_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.03 0.05"/>
      </geometry>
      <material name="white" />
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <!-- caster front joint -->
  <joint name="caster_front_joint" type="fixed">
    <parent link="robot_body_link"/>
    <child link="caster_front_link"/>
    <origin xyz="${length/2} 0 ${-height/2-0.025}" rpy="0 0 0"/>
  </joint>

  <link name="caster_front_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.05"/>
      </geometry>
      <material name="white" />
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.03 0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

</robot>